FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y python3 python3-pip python3-sphinx

# RUN mv /usr/lib/python3.12/EXTERNALLY-MANAGED /usr/lib/python3.12/EXTERNALLY-MANAGED.old
RUN pip install sphinxcontrib.tikz sphinxcontrib-bibtex sphinxcontrib-blockdiag
RUN apt install -y texlive-latex-base texlive-latex-extra texlive-latex-recommended latexmk texlive-lang-greek
RUN apt install -y doxygen

RUN apt install -y build-essential gcc-12 g++-12 libgtest-dev cmake
RUN apt install -y libboost-random-dev libboost-log-dev libboost-thread-dev libboost-filesystem-dev
RUN apt install -y flex bison
RUN apt install -y graphviz

COPY entry_doxygen.sh /latex.sh
ENTRYPOINT ["bash","/latex.sh"]