FROM ubuntu:latest

# Aggiorna i repository e installa i pacchetti necessari, incluso python3-venv
RUN apt update && \
    apt install -y build-essential gcc-10 g++-10 libgtest-dev cmake && \
    apt install -y doxygen indent python3-virtualenv python3-venv && \
    apt install -y libboost-random-dev libboost-log-dev libboost-thread-dev libboost-filesystem-dev && \
    apt install -y flex bison

# Crea l'ambiente virtuale Python e installa i pacchetti necessari
RUN python3 -m venv /env && \
    . /env/bin/activate && \
    pip install strictdoc

# Costruisci e installa GoogleTest
RUN cd /usr/src/googletest && cmake . && cmake --build . --target install

# Copia il file di entrypoint
COPY entry_doxygen.sh /entry.sh

# Configura la variabile di ambiente per il formato della lingua
ENV LANG en_US.UTF-8

# Definisci l'entrypoint
ENTRYPOINT ["bash", "/entry.sh"]
