FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y python3 python3-pip python3-sphinx

RUN mv /usr/lib/python3.12/EXTERNALLY-MANAGED /usr/lib/python3.12/EXTERNALLY-MANAGED.old
RUN pip install sphinxcontrib.tikz sphinxcontrib-bibtex sphinxcontrib-blockdiag
RUN apt install -y texlive-latex-base texlive-latex-extra texlive-latex-recommended latexmk texlive-lang-greek
RUN apt install -y doxygen

COPY entry_doxygen.sh /latex.sh
ENTRYPOINT ["bash","/latex.sh"]
